gilbreth-c002.rcac.purdue.edu
Total tasks: 4
Total tasks per node: 4
CPUs per task: 2
CUDA visible devices: 0,1,2,3
Number of nodes: 1
The following modules were not unloaded:
  (Use "module --force purge" to unload all):

  1) xalt/1.1.2
/usr/bin/uuidgen: /home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/libuuid.so.1: no version information available (required by /usr/bin/uuidgen)
num_proc        : 1
Traceback (most recent call last):
  File "../scripts/pretrain_wav2vec2.py", line 130, in <module>
    print(f"Process rank: {os.environ['RANK']}")
  File "/home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
num_proc        : 1
Traceback (most recent call last):
  File "../scripts/pretrain_wav2vec2.py", line 130, in <module>
    print(f"Process rank: {os.environ['RANK']}")
  File "/home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
num_proc        : 1
Traceback (most recent call last):
  File "../scripts/pretrain_wav2vec2.py", line 130, in <module>
    print(f"Process rank: {os.environ['RANK']}")
  File "/home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
num_proc        : 1
Traceback (most recent call last):
  File "../scripts/pretrain_wav2vec2.py", line 130, in <module>
    print(f"Process rank: {os.environ['RANK']}")
  File "/home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
srun: error: gilbreth-c002: tasks 0-3: Exited with exit code 1
